//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Stance struct {
	ID      *int32 `sql:"primary_key"`
	QueryID int32
	PartyID int32
	Text    *string
}
