// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"goth/.gen/model"
	"goth/internal/templates/components"
)

func Index(history []model.Query) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid w-full grid-cols-12 gap-20\"><div class=\"col-span-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.History(history).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"grid min-h-screen col-span-8 gap-4 py-4\"><div class=\"max-w-2xl space-y-4\"><div class=\"flex flex-col items-center space-y-2\"><h1 class=\"text-3xl font-bold tracking-tighter sm:text-5xl\">Position des partis politiques</h1><p class=\"text-gray-500 md:text-xl/relaxed dark:text-gray-400\">Entre un sujet pour connaître la position des partis politiques</p></div><form hx-get=\"/stances\" hx-target=\"#stances\"><div class=\"w-full bg-white border border-gray-200 shadow-sm rounded-xl dark:border-gray-800 dark:bg-gray-950\"><div class=\"grid w-full grid-cols-2\"><input class=\"flex w-full h-12 px-3 py-2 text-sm font-semibold text-gray-900 placeholder-gray-400 bg-white border-0 rounded-md appearance-none border-input ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-950 dark:placeholder-gray-500 dark:text-gray-50\" placeholder=\"Entrez un sujet...\" name=\"query\" type=\"search\"> <button class=\"inline-flex items-center justify-center w-full h-12 px-4 py-2 text-sm font-medium transition-colors rounded-md whitespace-nowrap ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50\">Chercher</button></div></div><img id=\"spinner\" class=\"htmx-indicator\" src=\"/static/svg/ring.svg\"></form><div id=\"stances\"></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
